require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'mPathe' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  #   post_install do |installer|
  #     flipper_post_install(installer)
  #   end
  # end
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RCTYouTube', :path => '../node_modules/react-native-youtube'

  pod 'react-native-smtp', :path => '../node_modules/react-native-smtp'

  pod 'RNSmtpMailer', :path => '../node_modules/react-native-smtp-mailer'

  pod 'react-native-voice', :path => '../node_modules/@react-native-community/voice'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

end
